name        : curl
version     : 7.83.0
release     : 1
summary     : A utility for fetching files from remote servers
license     : 
    - MIT
homepage    : https://curl.se/
description : |
    A utility for fetching files from remote servers.
source   :
    - https://github.com/curl/curl/releases/download/curl-7_83_0/curl-7.83.0.tar.xz: bbff0e6b5047e773f3c3b084d80546cc1be4e354c09e419c2d0ef6116253511a
builddeps   :
    - make
    - clang
    - lld
    - llvm
    - libcxx-devel
    - jansson-devel
    - nghttp2-devel
    - openssl-devel
    - zlib-devel
    - zstd-devel
setup       : |
    %configure --disable-static \
        --with-openssl \
        --with-ca-bundle=%(vendordir)/ssl/certs/ca-certificates.crt
build       : |
    %make
install     : |
    %make_install
